# Generated by Django 5.0.1 on 2024-03-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_linear_long_quote_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertdata',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertdata',
            name='wpm',
            field=models.IntegerField(default=0),
        ),
    ]
