# Generated by Django 5.0.1 on 2024-03-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usertdata_accuracy_alter_usertdata_wpm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertdata',
            name='user',
        ),
        migrations.AddField(
            model_name='usertdata',
            name='username',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
